posConfig = {
	TEMPLATE_DASHBOARD_VERSION: 1.01,
	TEMPLATE_LOGIN_VERSION: 1.01,
        TEMPLATE_SIDEBAR_VERSION: 1.01,
        TEMPLATE_HEADER_VERSION: 1.01,
        TEMPLATE_CABINET_DETAILS_VERSION: 1.01
};